### PR TITLE
Implement History and Undo commands

### LINKED ISSUE #79: Implement Undo Command
`Undo` command will restore the state of the address book before the previous command was executed.

### LINKED ISSUE #133: Bug found in assign command
Null Pointer Exceptions encountered.

Steps to reproduce this bug:
1. Download the latest `.jar` file.
2. `add i/A n/A m/A`
3. Close app
4. Reopen app
5. `assign m/CS2100 tn/x`
6. Null Pointer Exception (Output display does not show results even tho task is assigned)
7. Reopen app
9. Task disappears

Steps to "fix" the bug:
1. `delete 1`
2. `assign m/CS2100 tn/x`
3. Works now

Is it something to do with how we deal with optional fields?

Might be related to the bug in #120.

### PR DESCRIPTION
**Pull request by brelkh**
**`History` command:**
Uses a class called `CommandHistory` in `model` to store the previously used commands for each new user session. Calling `history` displays a list of all the successfully executed commands used so far. If a command is not successfully executed, it will not appear in history (similar to arrow key functionality). As a side note, `undo` will revert the changes of a command and also remove it from the `CommandHistory`.

**`Undo` command:**
'undo' uses the class `AddressBookHistory` (which stores a copy of `AddressBook` for each command called) and reverts the current `AddressBook` to the previous one when called.

Admittedly, this uses a lot of memory especially when there are a large number of calls in a session (eg. more than 100). While it was an alternative design consideration to parse a certain command to be undone and do the opposite of that command, that would be a lot more tedious to implement and maintain. Although I haven't encountered any slowing yet, a current workaround would be to close and reopen TAPA to reset `AddressBookHistory`.

Additionally, commands that don't alter `AddressBook` like `list`, `manual`, and `history` can also be undone (although it may be more intuitive that only commands like `add`, `edit`, and `delete` should be undoable). The problem there would be that focusing on only certain commands that can be undoable will be harder to maintain. Also, a perk of the current implementation is that easily overlooked commands can still be undone if needed. Eg. `list` does resort the `PersonList` alphabetically and that can be undone if needed.

That being said, modifications were made to `ConfirmClearCommand` to reset the `CommandHistory` and `AddressBookHistory` so that `undo` can no longer be called after the user calls and confirms `clear`.

**Limitations:**
1) Clear command cannot be undone. (Since clear command already requires user confirmation, this should be okay.)
2) However, if the user inputs `clear` and does not `confirm`, the `clear` command will remain visible in history. The user can then also undo it, but since the `clear` didn't alter TAPA, `undo` doesn't change anything back.
3) A user cannot undo a undo (ie. redo).

**Notes:**
1) We didn't plan to have a `history` command, but I used it as a stepping stone for `undo`. Lemme know if you think it should be removed though!
2) `Manual` command and messages have been updated

**Todo:**
1) Implement test cases for `History` and `Undo`
2) Update UGDG with `History` and `Undo` 
3) Fix failing CI checks: (Done!)
- [x] Update Model Stub with new methods
- [x] Update failing tests with new expected results

Closes #79 and closes #133

### CODE REVIEW

**Review by Korochii — COMMENTED** [review]
Interesting approach!
However, I think the `undo` command does not work for some commands (specifically the task-related ones like assign/mark/unmark).
Trying to figure out why this happens as well and will update you if I can find a way to fix this. 

UPDATE: I have a feeling its smt to do with how we assign/modify task instead of it being a bug for `undo`, as this is currently happening:
1. Original AB
2. `mark` command called
3. New AB has the updated task list (which is expected). However, the prev AB (original)'s task list is also being updated due to both AB sharing the same task list?

**Comment by Korochii** [comment]
> > Interesting approach! However, I think the `undo` command does not work for some commands (specifically the task-related ones like assign/mark/unmark). Trying to figure out why this happens as well and will update you if I can find a way to fix this.
> > UPDATE: I have a feeling its smt to do with how we assign/modify task instead of it being a bug for `undo`, as this is currently happening:
> > ```
> > 1. Original AB
> > 
> > 2. `mark` command called
> > 
> > 3. New AB has the updated task list (which is expected). However, the prev AB (original)'s task list is also being updated due to both AB sharing the same task list?
> > ```
> 
> I managed to fix this by changing the getCopy() method in Person to the following:
However, I'm not sure if this is the correct fix as it causes 20+ existing testcases to fail (or are we supposed to modify these testcases?)

**Comment by brelkh** [comment]
@Korochii Thanks for finding this bug and for the advice! I'm looking into it now 👍

**Comment by brelkh** [comment]
@Korochii I've come to the same conclusion as you - I overlooked the fact that each of the previous saved AB's `TaskList` point to the same `ArrayList`. 

I agree that the way to correct this would be to have each copy of `Person` perform a deep copy of `TaskList`. After copying your suggestion for `Person:getCopy()`, the assign/mark/unmark commands work as expected.

I updated `Person:equals()` as well, however, I did not use your suggestion. I'm not sure if it's a mistake/typo, but your suggestion uses `==` rather than `.equals()` to check for equality between `Phone`, `TelegramHandle` and `Email` objects. I think these might have caused the failed testcases because the testcases seem to have passed on my machine.

I'll commit these changes to this PR for the Github CI checks.

**Comment by Korochii** [comment]
> @Korochii I've come to the same conclusion as you - I overlooked the fact that each of the previous saved AB's `TaskList` point to the same `ArrayList`.
> 
> I agree that the way to correct this would be to have each copy of `Person` perform a deep copy of `TaskList`. After copying your suggestion for `Person:getCopy()`, the assign/mark/unmark commands work as expected.
> 
> I updated `Person:equals()` as well, however, I did not use your suggestion. I'm not sure if it's a mistake/typo, but your suggestion uses `==` rather than `.equals()` to check for equality between `Phone`, `TelegramHandle` and `Email` objects. I think these might have caused the failed testcases because the testcases seem to have passed on my machine.
> 
> I'll commit these changes to this PR for the Github CI checks.

Nice! Seems like it had passed the CI checks. The reason why I changed to `==` was because I was facing Null Pointer Exceptions in this scenario:
1) Person A has null phone
2) Person B has a valid phone
3) Assign/mark/unmark task for Person B
4) NullPointerException when comparing phone
Maybe I will check again when I'm free later 😃

**Comment by Korochii** [comment]
> > @Korochii I've come to the same conclusion as you - I overlooked the fact that each of the previous saved AB's `TaskList` point to the same `ArrayList`.
> > I agree that the way to correct this would be to have each copy of `Person` perform a deep copy of `TaskList`. After copying your suggestion for `Person:getCopy()`, the assign/mark/unmark commands work as expected.
> > I updated `Person:equals()` as well, however, I did not use your suggestion. I'm not sure if it's a mistake/typo, but your suggestion uses `==` rather than `.equals()` to check for equality between `Phone`, `TelegramHandle` and `Email` objects. I think these might have caused the failed testcases because the testcases seem to have passed on my machine.
> > I'll commit these changes to this PR for the Github CI checks.
> 
> Nice! Seems like it had passed the CI checks. The reason why I changed to `==` was because I was facing Null Pointer Exceptions in this scenario:
> 
>     1. Person A has null phone
> 
>     2. Person B has a valid phone
> 
>     3. Assign/mark/unmark task for Person B
> 
>     4. NullPointerException when comparing phone
> 
> 
> Maybe I will check again when I'm free later 😃

@brelkh Anyways good news! It seems like this case works after I redownloaded the updated code (maybe I might have messed something up on my side haha). I will go ahead and continue to review/approve this PR :smiley:

**Comment by brelkh** [comment]
@Korochii Alright, thanks a bunch!

**Comment by Korochii** [comment]
Wait nvm for some reason, I ended up getting Null Pointer Exceptions again...
image

Steps to reproduce this bug:
1. Create a `Person` with fields ("AZ", "A", "CS")
2. `list`
3. `assign i/AZ tn/m`
4. `mark i/AZ idx/1`
5. `unmark i/AZ idx/1`
6. `mark i/AZ idx/1`
7. `undo`
8. `undo`
9. `undo`
10. `undo`
11. `assign i/A0000000Z tn/m`

**Comment by Korochii** [comment]
Wait nvm for some reason, I ended up getting Null Pointer Exceptions again...
image

Steps to reproduce this bug:
1. Create a `Person` with fields ("AZ", "A", "CS")
2. `list`
3. `assign i/AZ tn/m`
4. `mark i/AZ idx/1`
5. `unmark i/AZ idx/1`
6. `mark i/AZ idx/1`
7. `undo`
8. `undo`
9. `undo`
10. `undo`
11. `assign i/A0000000Z tn/m`

**Review by Korochii — APPROVED** [review]
Otherwise, LGTM and feel free to merge when ready!

(Hope I didn't miss out any small issue haha)

**Comment by medajet** [comment]
> Wait nvm for some reason, I ended up getting Null Pointer Exceptions again... image
> 
> Steps to reproduce this bug:
> 
> 1. Create a `Person` with fields ("AZ", "A", "CS")
> 2. `list`
> 3. `assign i/AZ tn/m`
> 4. `mark i/AZ idx/1`
> 5. `unmark i/AZ idx/1`
> 6. `mark i/AZ idx/1`
> 7. `undo`
> 8. `undo`
> 9. `undo`
> 10. `undo`
> 11. `assign i/A0000000Z tn/m`
> 
> Like its damn weird cos it works sometimes but sometimes it doesnt... UPDATE: It kinda works now and I cant reproduce this bug anymore, so shld we just go with this implementation first and maybe fix it in v1.4 if we really need to?

I've just tried this and am not able to reproduce the bug, so I think it might be fine for now.

**Comment by Korochii** [comment]
> > Wait nvm for some reason, I ended up getting Null Pointer Exceptions again... image
> > Steps to reproduce this bug:
> > 
> > 1. Create a `Person` with fields ("AZ", "A", "CS")
> > 2. `list`
> > 3. `assign i/AZ tn/m`
> > 4. `mark i/AZ idx/1`
> > 5. `unmark i/AZ idx/1`
> > 6. `mark i/AZ idx/1`
> > 7. `undo`
> > 8. `undo`
> > 9. `undo`
> > 10. `undo`
> > 11. `assign i/A0000000Z tn/m`
> > 
> > Like its damn weird cos it works sometimes but sometimes it doesnt... UPDATE: It kinda works now and I cant reproduce this bug anymore, so shld we just go with this implementation first and maybe fix it in v1.4 if we really need to?
> 
> I've just tried this and am not able to reproduce the bug, so I think it might be fine for now.

Thanks for trying it out too!

**Comment by brelkh** [comment]
@Korochii @medajet Thanks guys, but oooohhh yikes, following Yan Long's steps, I reproduced the null pointer exception. Looking into it now!

**Comment by Korochii** [comment]
Perhaps we might wanna test on the `.jar` file instead since this is what the testers will be using as well

**Comment by Korochii** [comment]
Hi @brelkh , could you try if this fix works (on #133 as well since they are related I think)?

For `Phone.java`, change the `equals` method to:
```
        if (other == this) { // short circuit if same object
            return true;
        }
        if (!(other instanceof Phone)) { // target object is of different type
            return false;
        }

        Phone targetObject = (Phone) other;

        if (targetObject.value == null && this.value == null) {
            return true;
        } else if (targetObject.value == null) {
            return false;
        } else if (this.value == null) {
            return false;
        } else {
            return value.equals(targetObject.value);
        }
```
For `Telegram.java`, change the `equals` method to:
```
if (other == this) { // short circuit if same object
            return true;
        }
        if (!(other instanceof TelegramHandle)) { // target object is of different type
            return false;
        }

        TelegramHandle targetObject = (TelegramHandle) other;

        if (targetObject.telegramHandle == null && this.telegramHandle == null) {
            return true;
        } else if (targetObject.telegramHandle == null) {
            return false;
        } else if (this.telegramHandle == null) {
            return false;
        } else {
            return telegramHandle.equals(targetObject.telegramHandle);
        }
```
For `Email.java`, change the `equals` method to:
```
if (other == this) { // short circuit if same object
            return true;
        }
        if (!(other instanceof Email)) { // target object is of different type
            return false;
        }

        Email targetObject = (Email) other;

        if (targetObject.value == null && this.value == null) {
            return true;
        } else if (targetObject.value == null) {
            return false;
        } else if (this.value == null) {
            return false;
        } else {
            return value.equals(targetObject.value);
        }
```

**Comment by brelkh** [comment]
@Korochii While I couldn't consistently trigger the null pointer exception before, after adding your suggestions, I can't seem trigger it at all. That may have been the fix, thanks!

**Pull request merged**
